spring.application.name=task-management-api

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://taskmanager_user:vW3aRV2wmj1nQsNW@cluster0.hwlz1t0.mongodb.net/taskdb?retryWrites=true&w=majority&appName=Cluster0

# Server Configuration
server.port=8080

# Jackson Date Format
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
spring.jackson.time-zone=UTC

# Logging (optional - helps debug MongoDB connection)
logging.level.org.springframework.data.mongodb=DEBUG

